### ISSUE TITLE
Gulp doesn't watch .pug files for changes

### ISSUE THREAD

**Issue by eshnil** [mathigon/textbooks#76]
I was trying to customize the `content/transformations/components/wallpaper.pug` file, but noticed that Gulp doesn't watch files with .pug extension for changes to auto-run the parser and renderer. Here's the Gulp config: https://github.com/mathigon/textbooks/blob/master/gulpfile.js#L49-L53

This would be useful to have. Currently, I need to run `rm content/.cache.json && npm start` after every change in these .pug files.

**Comment by plegner** [comment]
Thanks for reporting this! It's actually quite a complex issue, because the parser doesn't know which courses it needs to re-compile when a PUG file changes. PUG files might be imported by multiple different courses, but always recompiling ALL of them would be very inefficient.

I will look into this some more, but for now, I'd recommend just making a small change to the `content.md` file of the course you're working on (e.g. adding an empty line somewhere). That will force a recompile, and is much easier than deleting the cache and restarting the server.

**Comment by plegner** [comment]
Fixed now!
